[package]
name = "crestron-load-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
eframe = { version = "0.36.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
if-addrs = "0.15.0"
rfd = "0.17.2"
russh = { version = "0.63", default-features = false, features = ["ring", "rsa", "flate2"] }
russh-sftp = "3"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.11.0"
socket2 = "0.6.1"
tokio = { version = "1", features = ["rt", "net", "io-util", "time", "fs"] }
